### ISSUE TITLE
[Not Issue] Works fine in Wayfire

### ISSUE THREAD

**Issue by aurkaxi** [MarSoft/upwork-wayland#3]
I tried some other packages but this one... oh man.. this works out of the box. 9 month ago last commit but still no issue. muah

**Comment by MarSoft** [comment]
Thank you for your kind words! I'm glad that my code was useful.
Actually, there *are* newer commits in `waybar` branch which adds support for a custom widget in `waybar` statusbar. But I don't yet consider it ready for everyone so I didn't merge it into the `master` branch.
And the main logic "just works", that's why there are no newer commits in `master`.
